export const CREATE_LENDER_START = "CREATE_LENDER_START";
export const CREATE_LENDER_DONE = "CREATE_LENDER_DONE";
export const CREATE_LENDER_FAIL = "CREATE_LENDER_FAIL";
export const CREATE_BORROWER_START = "CREATE_BORROWER_START";
export const CREATE_BORROWER_DONE = "CREATE_BORROWER_DONE";
export const CREATE_BORROWER_FAIL = "CREATE_BORROWER_FAIL";
export const GET_LOANS_START = "GET_LOANS_START";
export const GET_LOANS_DONE = "GET_LOANS_DONE";
export const GET_LOANS_FAIL = "GET_LOANS_FAIL";

export const GET_MARKETPLACE_LOGS_START = "GET_MARKETPLACE_LOGS_START";
export const GET_MARKETPLACE_LOGS_DONE = "GET_MARKETPLACE_LOGS_DONE";
export const GET_MARKETPLACE_LOGS_FAIL = "GET_MARKETPLACE_LOGS_FAIL";

export const CLEAR_FORM = "CLEAR_FORM";
